### ISSUE TITLE
Defintions of reverse-isms is counter productive

### ISSUE THREAD

**Issue by frivoal** [w3c/PWETF#121]
Let me start with a few disclaimers, so that my intent is not misunderstood:

* This point is not the most important in the document, and I thought the more important points were well addressed. Discussing this point is not meant to raising it above the rest. I just think the rest is good.

* I acknowledge by own biases and privilege, and that makes me reluctant to bring up this issue, as the CEPC rightfully prioritizes the safety of individuals within marginalized communities, and I don't want to highjack that. Nonetheless I think there is a weakness, and since feedback is being sought, I thought I'd share.

* I do not believe that there is a prevalent problem of "racism against whites", of "sexism against men", of csiphobia, or of heterophobia, nor do I think that we need to take any specific step to protect against these.

* I agree that power imbalance form a major component in many acts of racism / sexism / homophobia / transphobia / ableism and other -isms and -phobias.

* I agree "Reverse *-isms" is not a valid concept.

However I think there is a problem is with the [definition of reverse-isms as included in the glossary](https://w3c.github.io/PWETF/#dfn-reverse-isms). I take no particular joy at debating the essence of what racism is, but since the CEPC is writing down a definition, and that the enforceability of disciplinary actions by W3C depend on the CEPC, I think this matters.

In my view, racism, sexism, homophobia, or transphobia, etc. are discrimination / abuse / harassment / hatred / etc on the basis of perception of a distinction of race, sex, gender, sexual orientation, etc. being hatred based on (perceived) differences, they can occur independently of power imbalances. A power imbalance is often involved, is indeed directional, and gravely compounds the problem. But it is an aggravating factor, not a necessary component.
 
As it is, the proposed CEPC states in the definition of reverse-isms that hatred / bigotry / abuse towards someone who has the upper hand in a power dynamic will not be considered racism, sexism, etc. Depending on whether #117 is accepted or not, this either implies, or is explicit, that the W3C will not act against those.

Just because these problems are much more frequent and much more damaging when they occur towards members of marginalized communities does not mean we should make them explicitly allowed in other situations.

We absolutely should make sure that acts intended to protect marginalized individuals/communities are not construed as aggression themselves, and that claims that they are can be dismissed. But we should say so directly, and this doesn't need introducing terms which we then define as being meaningless, while accidentally condoning abuse as long as it's abuse of someone otherwise privileged.

If someone is genuinely being abused and looks at the code of conduct for help, they should not find there that "abuse in general is bad, but your particular problem isn't valid".

In order to preserve what I believe is the intent (preventing acts protecting marginalized individuals/communities from being construed to be abuse), while limiting undesirable side effects (actual abuse against non marginalized people being construed as OK) I suggest replacing the reference to reverse-isms in the list of situations at the end of section 3 (first line given for context):

> [...] reserve the right not to take further actions on complaints regarding: 
> * "Reverse" -isms, including "reverse racism," "reverse sexism," and "cisphobia".

with

> [...] reserve the right not to take further actions on complaints regarding: 
> * Non-threatening acts aimed at protecting marginalized communities or individuals (e.g. safe spaces or other supportive accommodations, etc.)

and removing the definition of "reverse-ism" from the Glossary.

**Comment by wareid** [comment]
First, some recommended reading: 
http://www.aclrc.com/racism-and-power
http://www.aclrc.com/myth-of-reverse-racism
https://www.kobo.com/ca/en/ebook/white-fragility

We've discussed the wording of the reverse-*isms section quite extensively, and no doubt it is a difficult topic to discuss. The most recent addition to the wording is probably the clearest, and maintains our position the best. Your proposed wording runs the risk of weakening the statement again, while also introducing new terminology to the glossary (what does "threatening" mean in the context of the CEPC?), opening up to even more discussion about definitions and what is considered "threatening" or "non-threatening". 

It's important to note that the wording specifically says that the enforcers have the option to either take action or not take action. We have further work to do regarding who the enforcers are and training them for these roles, but the language is clear enough for the purpose. 

We have chosen definitions for racism and racial prejudice that are in line with accepted practice (see the first link I posted above). Your personal definition of racism aligns more with racial prejudice, whereas the broadly accepted definition of racism today is centred on power imbalances. I really recommend reading what I've provided above as they are excellent resources. 

The last point I want to make is about your disclaimer. The code covers many things that some have decried as "I've never seen this" or "I don't think this happens at the W3C". If that is true, then that is wonderful. However, I do not think it is, it is more likely going unreported, and the real reporting is the individual or individuals ending their participation. A CoC should be more than reactionary, we should not wait to have something happen before we do something about it. This document should be an indicator to people or groups in the W3C that this is who we want to be, it should be aspirational. For many in marginalized communities it's a signal that there is protection here, and that god forbid something should happen, they have recourse to seek justice.

**Comment by frivoal** [comment]
Thanks, these were very interesting reads (though I haven't ordered the book yet).

Under this nomenclature, what I am concerned is indeed about racial / sexual / etc prejudice more than racism / sexism / …, and about the risk that this phrasing in the CEPC would cause people to misunderstand that expressions of racial / sexual / etc prejudice are non-problematic as long as they don't flow downwards a power hierarchy. Whether that misunderstanding would be among participants who may feel legitimized in bad behavior by this code, or among ombuds / w3c management who may mishandle complaints, either way that would be regrettable.

I will note though that while this distinction between racism and racial prejudice seems like a useful one, I am not quite sure that it is sufficiently broadly known to be able to rely on that distinction being understood: for instance, wikipedia doesn't seem to clearly distinguish, and in the other languages I speak fluently (including my native language), I am unsure the same distinction would survive translation. I now see that it is explained in the glossary (at least for racism / racial prejudice, even if not for the equivalent distinction for sexual prejudice / sexism), but even for someone who was reading the document top to bottom, that was easy to miss.

I'll also note that racism / racial prejudice is understood differently in different cultures, and this analysis / set of definitions seems quite American to me. I am not trying to say that things are better elsewhere or that other understandings of the issue are to be preferred, but I am concerned that even among people who are sensitive to this topic, the distinction you are trying to convey and to rely on may be lost, hence my worry that this may be read as giving a free pass to prejudice in certain circumstances.

Even if I missed on the particularly distinction that were being expressed here, the difficulty to state this clearly is kind of why I was attempting to remove the indirection from the list at the end of 3.2 to a definition of reverse-isms, as that definition might need to turn into a dissertation of its own to carry enough nuance and to be understandable across cultures, and was attempting instead to explicitly and directly protect "[...] acts aimed at protecting marginalized communities or individuals".

Beyond this high level point, here are a few more narrow responses to other points you made:

> (what does "threatening" mean in the context of the CEPC?)

Fair point. Dropping "non-threatening" from that sentence would remove this source of confusion without dropping anything I'd deem essential there.

> The last point I want to make is about your disclaimer. The code covers many things that some have decried as "I've never seen this" or "I don't think this happens at the W3C". If that is true, then that is wonderful. However, I do not think it is.

I am not completely sure, but I think you're reacting to my "do not believe that there is a prevalent problem [...] nor do I think that we need to take any specific step to protect against these."

If so, I was not attempting to say that I don't believe such problems never happen. Very much the contrary, I believe that all sorts of problems of abuse do exist, including outside of the context of marginalized communities or individuals. I just think that in contrast to abuse targeted at marginalized communities or individuals, the problem of abuse of otherwise privileged people is *comparatively* rare enough that it can be handled by generic mechanisms, and does not need to be highlighted nearly as much. As you say, for many in marginalized communities, a CEPC that focuses on their needs is a useful and welcome signal. But as the CEPC is not merely for signaling, but also works as the basis of enforcement, I worry that the reverse-ism definitions undermines the generic mechanisms, which need to exist, even if they don't need to be highlighted. That's what drove me to raise this issue.

**Comment by fantasai** [comment]
1. The distinction PWE is attempting to draw here between "racism" and "racial prejudice" might be useful in academic documents, but it is not compatible with colloquial usage of the term "racism" (see [Merriam-Webster](https://www.merriam-webster.com/dictionary/racism), which very clearly defines them as equivalent). Using terms in a refined way in a spec, and taking care to define those terms is fine _but only so long as the colloquial semantics of those terms do not interfere with understanding the document_. A CEPC document in particular needs to be understandable to normal people reading at a normal level, not just to the editors or to people who spend three hours reading academic materials in preparation.
2. The purpose of the CEPC is not just as an enforcement tool, but also to signal to people of what is considered acceptable behavior here. Its primary interpreters are the members of the community, in fact, not the enforcers. Not only does it need to be understandable to them, it should have the goal of making each participant feel as if they are participating on equal footing with the others (as that is fundamentally the goal of the CEPC in general, I hope we agree on this). Any wording which implies the opposite or introduces doubt about it undermines that goal. It should be abundantly clear, without a doubt, for example that pervasive discussions about how men are inherently unsuitable for leadership positions are equally incompatible with the CEPC as such discussions about how women are inherently unsuitable for leadership positions. And the wording here, because of the colloquial understanding of "racism" and "sexism" and "reverse", does leave doubts about that.
3. To the extent that there are particular concerns that PWE was trying to address with this wording, those intents are not made clear through this clause. Tzviya listed allowing enforcement of the CEPC and addressing retaliation, for example, as the reasons for this clause. It would make more sense to list those reasons explicitly rather than referencing a term defined in the glossary to be meaningless and assuming these intents will be understood by all to have been implied.

As a spec editor, it is my job to ensure that anyone making a good faith effort to understand my document is able to correctly interpret it. Even invalid issues are an opportunity to evaluate whether the document needs improvement to help the next person figure out the nuance correctly without my help. To the extent that this bullet point is causing concern or confusion (as it clearly seems to be doing), it is imho PWE's job to improve the text so that PWE's intent can be understood with ease. We should all be able to arrive at a shared understanding of the CEPC without anyone needing to jump through mental hoops, and ideally in a way that survives translation!

**Comment by TzviyaSiegman** [comment]
Thanks @fantasai. The glossary in CEPC includes terms that exist in the CEPC and may not be familiar, especially in context. We are also lining up translators.

I think that we should change the term "Racial Prejudice" to "Prejudice" as the definition provided is broader than race. Further, the term used in the text is "prejudice". 

The term "reverse -isms" is included because it is used, not just in the CEPC but in many other CoCs, and colloquially. I am working on creating a PR that removes the consequences and sticks to definitions.

An additional comment is that part of the role of a code of conduct is to educate. Sometimes codes of conduct make us aware of things with which we are not familiar. We all have biases. Sometimes a CoC makes us more aware of them. I certainly learned a lot about my own biases while doing research for CEPC.

**Comment by wareid** [comment]
I did some quick research on the usage of reverse-*isms in other CoCs and came up with this list: 
https://dev.to/code-of-conduct
https://immersive-web.github.io/homepage/code-of-conduct.html <-- already in use within the W3C
https://wealljs.org/code-of-conduct

**Comment by fantasai** [comment]
> we are technical people, but we need to prioritize the "people"

Which is why it needs to be written in a way that's understandable to the worldwide W3C community who is reading and interpreting it, rather than in a technical way which satisfies American sociologists and the PWECG members who have been immersed in it for months but is easily misinterpreted by anyone else. https://github.com/w3c/PWETF/issues/121#issuecomment-591253780

**Comment by TzviyaSiegman** [comment]
this was resolved with #117 _
