### ISSUE TITLE
Document against misuse of policy

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/PWETF#189]
As the CEPC has become more socialized, people refer to it more in evaluating the behaviour of themselves and others. This has led to greater awareness of appropriate behaviour as well as increased reaction to inappropriate behaviour. That is a goal of the policy and has facilitated important conversations. But over time, I've been seeing that people invoke the CEPC on somewhat routine disagreements if people become impassioned. Raising issues as a "CEPC complaint" invokes a full formal process of discussions, warnings, and other actions, but often the issues could be as effectively dealt with informally. While I cannot state assuredly that this has happened, I have begun to worry that people may be starting to use CEPC complaints as a tool in an arsenal of setting technical direction in our standards world. I think the policy should have some wording about invoking formal complaint procedures in more extreme scenarios and referring to informal mechanisms most of the time.

**Comment by wareid** [comment]
Unfortunately this issue is being discussed in multiple places, but for the sake of pertinence and progress, I'm going to address the content of the issue and not some of the other assertions regarding the CEPC. 

So this sounds like a need. However, we need information. Here in the issue (and [in the email thread](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021OctDec/0210.html), apologies to those unable to view this due to permissions), it has been asserted that some people are either using the CEPC to stifle debate or to silence dissent. 

This is an incredibly serious assertion, and one we should take seriously. When we worked on the CEPC, it was something we discussed frequently, because the spirit of the document was to create a safe and positive working environment for all. 

We need information though, we need to understand which sections are being misused, how people are interpreting the document to abuse it. I understand the challenge of not revealing details here, and it is not what we need, what we need is examples the reflect the real-world issues. So for us to proceed, we need to actually understand the issues at play.

@msporny @michael-n-cooper could you share some instances you have either witnessed or handled, this would provide us with something to discuss (again, these can be anonymized, or abstractions of things that actually occurred, we need to respect the delicacy of the situations). If not here, I am sure we can find a way to get this information into the hands of PWE so that we can discuss how to proceed.

**Comment by msporny** [comment]
> I understand the challenge of not revealing details here, and it is not what we need, what we need is examples the reflect the real-world issues. 

Agreed and understood. I've tried writing up the three instances for over an hour now and keep coming to something that would easily and publicly identify the parties involved. It's not appropriate for that to happen at this point in time (if ever), so please give me a bit of time to try and frame it in a way that protects the parties involved while also not making it sound so generic and theoretical as to be easily dismissed.

**Comment by jwrosewell** [comment]
Perhaps the input could be provided anonymously to W3C Team or the PWETF chairs rather than publicly via GitHub? I've offered to provide input to the chairs.

FYI The lack of options for [anonymous input](https://github.com/w3c/w3process/issues/469) were raised in Process CG where it has been suggested the issue should move to the AB.

**Comment by TzviyaSiegman** [comment]
@michael-n-cooper wrote:

> But over time, I've been seeing that people invoke the CEPC on somewhat routine disagreements if people become impassioned."t over time, I've been seeing that people invoke the CEPC on somewhat routine disagreements if people become impassioned.

So, let's break this down:

1. Person A becomes impassioned about Super Cool Tech
2. Person B is impassioned about Awesome Tech
3. Person A and B have a "routine" disagreement about whether to encode Cool or Awesome into the spec

Is this routine or is this a CEPC violation? 

It depends on so many variables! There is no way for me to respond to this without being in the meeting and observing tone, attitude, choice of words, facial expression. There are many situations when it is exactly the kind of thing we were hoping to warn about when we added to the list of unacceptable behaviors (such as "Patronizing language" and "deliberate intimidation"). However, it is also possible to do this in an extremely respectful manner. What I will never know is what is happening inside someone else's head. Maybe my choice of words is difficult for someone because of something that happened in the past? Maybe I am bad at picking up on cues that it's time to move the discussion forward, and it would be better to vote on this topic over email. There are lots of things to consider when running a meeting as well as when making an accusation. 

The CEPC is a set of guidelines to help us understand how we can be more respectful of one another. If you are able to help us improve the language so that it cannot be abused, we welcome recommendations.

**Comment by TzviyaSiegman** [comment]
@jwrosewell wrote 
> Perhaps the input could be provided anonymously to W3C Team or the PWETF chairs rather than publicly via GitHub? I've offered to provide input to the chairs.
That option is always open in the public review period.

**Comment by jwrosewell** [comment]
FWIW I can't recall an incident where the CEPC was cited in a meeting during verbal debate. I have seen it cited many times in written communication.

**Comment by wareid** [comment]
> FWIW I can't recall an incident where the CEPC was cited in a meeting during verbal debate. I have seen it cited many times in written communication.

In this case, if it's happening on a member or public list, there's archived records of it. If you have seen this in certain groups' threads (that again, do not need to be shared on github to at least shield somewhat), pointers would be helpful.

**Comment by dwsinger** [comment]
For most of CEPC, it only becomes a way to silence dissent if the message cannot be conveyed in a way that is acceptable.

However, there are some parts of CEPC, notably the 'sealioning' (a metaphor that I find obscure to this day, by the way), where the essence of the complaint is that someone is 'talking too much', and for that, the recourse is, of course, to talk less: not exactly silence, but certainly to 'turn down the volume'. This one still worries me. 

It's a chair skill to manage debate so that all voices are heard to the appropriate degree, and not to let all the air in the room be sucked up by one person. Is it a CEPC question, as such? I know plenty of people, including myself, who sometimes waffle and ramble when they should be silent and mentally forming a short but cogent point. And I have seen people intentionally try to dominate debate – but is this really in the same category as treating people (rather than technical points) differently based on non-relevant criteria (such as gender)? Or is it a chairing skills question?

**Comment by jwrosewell** [comment]
Others that I find concerning in the editors draft include;

"Gish Galloping" - who decides if the argument is weak? A well written charter should clearly point to scope, a W3C policy such as the following would determine it's importance. 

    a)            small impacts to a large number of people; and 
    b)            big impacts to a small number of people; 
    
    but not 
    
    c)            small impacts to a small number of people.

"Concern Trolling" - again a W3C policy will address whether the concern is valid within the scope and context of the W3C. For example; we don't have an agreed position on climate change. Some might consider the environmental impact of some proposals to be a concern, others may not. Who decides?

Overall I would prefer these phrases removed and replaced with text similar to the following.

    Wasting others time.
    * Repeating statements which have been shown to be false.
    * Re-raising questions that have already been answered.

I note this proposal was previously rejected.

**Comment by TzviyaSiegman** [comment]
All, there are several topics being discussed here. If you want to discuss the wording of CEPC, please open a new issue. If you want to discuss misuse of CEPC, please continue here.

**Comment by msporny** [comment]
@msporny wrote:
> ... please give me a bit of time to try and frame it in a way that protects the parties involved while also not making it sound so generic and theoretical as to be easily dismissed.

Finally, one that happened on the record between the Chair of one of the most notable groups at W3C and a prominent ex-W3C Staff member and current AC Representative for a multi-billion dollar corporation:

https://lists.w3.org/Archives/Member/w3c-ac-forum/2021OctDec/0262.html

Accusations being made are "sealioning" and "trolling" in response to an exceedingly short thread between the two individuals.

I'll continue to link to examples that I find in the wild here...

**Comment by TzviyaSiegman** [comment]
@msporny I don't think examples should be provided in this repo.

**Comment by msporny** [comment]
> @msporny I don't think examples should be provided in this repo.

Where should we put them?

**Comment by lutgendorff** [comment]
We’re going to close this topic as without additional evidence, it’s difficult to pursue this further.

As a general comment, there are aren’t necessarily clear cut boundaries in some of the issues where the CEPC is involved.  The CEPC assumes everyone _will accept and abide by community made decisions_. This is not something limited to the W3C CEPC, but generally where there are large communities and a code of conduct that needs to cover a wide range of behaviours.

There are always going to be ongoing disagreements within a large community. Some examples where this may lead to the CEPC being involved are where:

- the community / group has largely come to consensus and an individual or group  continually try to re-raise issues that have been settled, without any valid reason to reopen it (eg no security flaw or new technology that would merit reopening a discussion)
- a person is not acting in good faith, raising issues where there is no real concern but are doing so in an attempt to undermine community decisions or stall decision making
- there’s an attempt to derail a discussion, where consensus is going in a certain agreed direction, without any valid / substantial reason to change that direction

The main point being that the W3C works through consensus, if individuals disagree with that consensus and continually try to undermine that consensus, that can be a violation as they aren’t acting in good faith.

Consensus means that the group has decided on a direction, and has already accepted the potential risks / flaws with the decision, so they don’t have to be continually raised / reintroduced.

These decisions should generally be mediated by a chair of a group, for example, acknowledging the issue but that due to existing consensus, they are not going to allow that issue to be acted upon further. But as mentioned, sometimes there can be ambiguity. 

If someone believes it is a CEPC violation, they should follow the process to raise it as an issue. If someone is using the CEPC to stifle discussion, that can also be raised under the CEPC. The CEPC states that the list of unacceptable behaviour does not cover every case and needs to be assessed on an individual level. However, it does seem to fall under “deliberate  intimidation”, if they are threatening a violation but there is no actual violation.

**Comment by msporny** [comment]
> We’re going to close this topic as without additional evidence, it’s difficult to pursue this further.

I've tried to log at least three concrete demonstrations of evidence and was asked to not post it here (guidance which I agree with), but given no alternative place to put them.

I don't disagree with what was said in the previous comment by @lutgendorff.

My concern here is that the CEPC is being raised in ways where there is not a safety concern but as a tactic during a heated debate (a form a character assassination), and that harms the effectiveness of the CEPC when there is a real safety concern.

That said, I don't have the time to pursue this. I have logged my concern, noted that the issue is being closed because [additional evidence wasn't provided](https://github.com/w3c/PWETF/issues/189#issuecomment-986850322), and note that [when evidence was provided, we were asked to remove the evidence](https://github.com/w3c/PWETF/issues/189#issuecomment-966460659) (and [given no alternative place we could place that evidence](https://github.com/w3c/PWETF/issues/189#issuecomment-966462352)).

**Comment by TzviyaSiegman** [comment]
@msporny As @lutgendorff commented, almost all cases are already covered by CEPC. This comes down to chairing, training, and the ability to execute the existing CEPC. Any cases with which I am familiar would fall under "deliberate intimidation”. Please feel free to add a PR to CEPC if you think there is something explicit to add to the text.

**Comment by msporny** [comment]
> Any cases with which I am familiar would fall under "deliberate intimidation”. 

Ok, good. I was largely concerned that PWETF was unaware that the CEPC is being used as a form intimidation. If we have acknowledgement that PWETF is aware of that issue, that's most of what I was trying to get to in this issue. 

I'd classify it as roughly half being "deliberate intimidation" (in the worst cases) and half being "unintentional intimidation" (in the cases where a long-term W3C-er invokes CEPC against a new-ish W3C-er, not understanding the silencing effect it has on newer participants).

> Please feel free to add a PR to CEPC if you think there is something explicit to add to the text.

Ok, will do -- now that there is acknowledgement from PWETF that the issue exists.
