### ISSUE TITLE
CEPC: How to politely correct someone?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#226]
Version reviewed: https://www.w3.org/Consortium/cepc/cepc-20200716/

Section 3.2 advises against patronizing language.  Certainly I agree with that intent, but I am puzzled at this advice:

> Be aware that, regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow, and avoid such phrases. For example, beginning an interjection with "Well, actually..." can set this expectation and be taken as a sign of disrespect. 

How should I politely correct someone who has said something factually wrong?   If the person says that the sum of 27 plus 15 is 38, how would you recommend that I correct that person?  If the mistake is immaterial to the work at hand, then there may be no need to correct it.  But what if it matters?

The best way I currently know to handle a mistake like that is to briefly and directly correct the mistake and then continue, without belaboring it.  Something like "Well, actually 27 plus 15 is 42, so we'll need to allocate a few more buffers for X and Y . . . ".   If you find "Well, actually" patronizing, then what other phrases do you think would be better?

**Comment by cwilso** [comment]
"I believe 27 plus 15 is 42; can you check my math?"

**Comment by TzviyaSiegman** [comment]
Thanks @cwilso. This section of CEPC has been discussed extensively. There are many ways to get one's point across without being patronizing. One of the goals of CEPC is to educate. Perhaps @dbooth-boston, you were unaware that the phrase "well, actually" is extremely uncomfortable for many and will make people tune you out?

**Comment by rigow** [comment]
If there were only native English speakers in W3C, this type of sophisticated language refining would make sense. But the world is larger. So rather than concentrating on words that may not be meant in an offensive way by someone who has Japanese or Italian as their native language, we need to educate English native speakers to take things with a grain of salt IMHO.  And to politely hint that this could be seen as offensive by native speakers.

Because with this sort of finegrained language rules, W3C would be difficult for people below a C1 rating in English. They could fear to make this one remark that triggers the shitstorm. That's not really inclusive, isn't it?

I would therefore opt for a method and meta rules, rather than proscribing the absence of certain wordings. 

Just my 2 cents

**Comment by TzviyaSiegman** [comment]
Please see previous discussion about this topic at https://github.com/w3c/PWETF/issues/45

**Comment by dbooth-boston** [comment]
Thanks for the pointer to previous discussions.  

> The phrase "well, actually" has become code for "let me tell you that I'm smarter than you."

I was not aware of that, so I've learned something.  Thank you!

SUGGESTION 1: Since many people are unaware that "well, actually" is a trigger phrase, I think it would be helpful if that were stated explicitly in the document -- perhaps with a pointer to more explanation -- if that phrase is going to be used as an example of something to avoid.

But having read the thread at #45, I am still left with the feeling that I don't know a more recommended way to politely correct someone when they've made a mistake that is germane to the work at hand.  In fact, I strongly suspect that whatever phrase is recommended, if widely adopted, will soon be MISused to speak in a patronizing way, and will then become a new trigger term as the cycle continues.  

> "I believe 27 plus 15 is 42; can you check my math?"

"I believe" sounds okay to me, but "can you check my math" sounds problematic.  If we were talking about a complex equation, and I honestly was not sure of my math, then "can you check my math" would sound (to me) appropriate and not patronizing.  But that's not the scenario I was raising.  In this example "can you check my math" would sound VERY patronizing to me, because it is obvious that 27 plus 15 is 42.  To my mind, feigning uncertainty is patronizing because it is dishonest.  It implies that the listener must be treated with kid gloves.  As a listener, I would find that condescending.

SUGGESTION 2: Since trigger phrases are not necessarily related to patronizing language, I suggest addressing them separately, perhaps along these lines:

[[
* Microaggressions, which are small comments or questions, either intentional or unintentional, that marginalize people by communicating hostile, derogatory, or negative beliefs. Examples include:

  * Use of trigger language or phrases that are likely to offend or distract certain groups or individuals;  _(and add a link to explanation and evolving list of examples)_
  * Patronizing language or behavior, such as assuming that particular individuals are less competent based on their appearance, identity or any other irrelevant characteristic; or assuming that groups of people are technically unskilled (e.g., “So easy your grandmother could do it”).

]]

**Comment by wareid** [comment]
+1 to @cwilso's example as one of many ways to approach a conversation like this. 

Something I want to emphasize here is that the approach to both acceptable and unacceptable behaviours, and CEPC in general, is one that depends on context and good faith. We are working in a professional capacity with one another, like any other workplace. How something is said, and the context surrounding that situation is often more important than the words themselves. What we ask is that participants be considerate of how they address one another, and as we make clear in section 4, it is strongly recommended situations be dealt with quickly and politely so as to avoid conflict and misunderstanding. People are not actively looking for CEPC violations, and if a situation does come up where someone takes offense to what someone else has said, more often than not it can be dealt with in the moment. 

The purpose of using "well actually" in this context was to provide a common illustration of the point we were making about patronizing language, not to enshrine "well actually" as a phrase that could never be used. It can be problematic, but when it is there are additional context clues to contribute to that. It's also entirely possible to be patronizing to someone without ever using that phrase. The point about language and specificity also addresses @rigow's concerns, we would not want to suggest certain phrases are by default problematic regardless of the context of their usage by providing an ever updating list of examples. We avoided this practice in the development of CEPC because being overly explicit with examples would have created more problems than solutions. 

CEPC is not designed or meant to police language, it's role is to provide participants with guidance on what is and is not appropriate in our organization. It is also a signifier of our organizational values. If you're in a situation where you feel you need to correct someone, but are unsure if they would be welcome to that information, ask! There are many ways to have these conversations. CEPC is not an instruction manual, it's a map, the direction you take is up to you.

**Comment by dbooth-boston** [comment]
> The purpose of using "well actually" in this context was to provide a common illustration of the point we were making about patronizing language, 

I think I understand that now.  But for me at least, the current text fell short because I was not previously aware that "well actually" is a trigger term.  The current text seems to assume that the reader knows that it is, but many people don't -- even among people (like me) who are otherwise well educated and care about marginalized communities.

**Comment by dbooth-boston** [comment]
Some comments on the minutes of 17-Jan-2023, when this issue was discussed:
https://www.w3.org/2023/01/17-pwe-minutes.html

> tzviya: In section about patronizing language within "microaggressions," very long discussion here. I believe David's point is if you assume people don't understand it's insulting.

No, my point was the opposite.  Defining one's jargon is standard best practice in any presentation forum, and should *not* be viewed as insulting.  It is harmful to imply that it is insulting because doing so will discourage people from doing it, and that creates a *less* inclusive environment.

> cwilso: the proper response is to capture the piece about not preassuming for certain groups a level of understanding based on irrelevant factors (like demographics)

Yes, exactly.  It is okay -- and sometimes advisable -- to make assumptions about a group based on *relevant* factors; it is *not* okay to make assumptions based on *irrelevant* factors.  

> tzviya: "asking" is causing some issues?

Yes, that word also causes problems, because asking the audience if they understand your jargon, or are familiar with your topic, generally does not work.  They will almost always say yes even when they don't.  This happens both because they (wrongly) assume that their experience with the topic is the same as yours, and because they don't want to embarrass themselves by admitting ignorance.

SUGGESTION 2a: Replace the "Patronizing language or behavior:" bullet (and its three sub-bullets) with the following two bullets:

[[

  - Use of trigger phrases that are likely to distress or offend certain groups or individuals.

  - Patronizing language or behavior, such as assuming that particular individuals are less competent or skilled based on their appearance, nationality, gender identity or any other irrelevant characteristic.

]]

**Comment by nigelmegitt** [comment]
Also worth noting: #46 was merged without change in response to https://github.com/w3c/PWETF/pull/46#discussion_r273520758 so if we are looking at the wording again, please consider that. I do not know why that happened.
