### ISSUE TITLE
Code of conduct violation

### ISSUE THREAD

**Issue by jfinkhaeuser** [w3c/PWETF#306]
Hi!

This is probably not the right place to report this, but it's worth giving it a shot. I'd like to point you to RupertBenWiser/Web-Environment-Integrity#112

The repository outlines technology, specs and rationale for a feature being trialed in Chromium. Presumably, this is to be taken to W3C for standardization, as its boilerplate Code of Conduct references the W3C's code.

Unfortunately, the proposal is itself in deep violation of said code. The proposal seeks to offload attestation about the browser to an agent running on the user's machine, with the intent of giving websites the option to refuse service if such an attestation cannot be given.

The proposal is entirely opaque on the criteria such an agent might use to provide an attestation, but does bring the Google Play service into mention as a potential agent. Play contains and manages personal identifiable information (PII).

If the implication of this is that arbitrary system services with access to PII can be used to *exclude* individuals from service, this is deeply discriminatory, and thus a violation of the code of conduct.

Surely this is not something W3C working groups can bring to standardization?

**Comment by nigelmegitt** [comment]
>This is probably not the right place to report this

Agreed.

However, I think it may also be a misunderstanding of the role of the CoC.

My understanding of the CoC is that it's about how _people_ interact with other people in the course of working in W3C.

Contrastingly, problems with W3C _specifications_ are generally identified and shared during review phases of those specifications, either wide review or the more specific horizontal review covering topics such as privacy and security, or web architecture. Problems like those described in this issue should be picked up during such a review phase.

Unless the proposed text is being used by someone to behave towards someone else in a non-CoC-conformant way, it does not seem reasonable to claim that it's a CoC violation. Without discounting the possibility that a violation has occurred, having looked at the explainer and the spec in the linked proposal, I could not see any such cases.

Returning to the "right place to report", see https://www.w3.org/Consortium/cepc/#Reporting .

**Comment by jfinkhaeuser** [comment]
Thanks, that is helpful - I did not find that!

**Comment by wareid** [comment]
@jfinkhaeuser Thank you for closing, and for bringing this to us too. As Nigel explained, our focus is on interpersonal actions. 

As Nigel also explained, should this proposal get to the point of a specification track document, W3C horizontal review would come into effect. Even earlier than that, a proposal like the one you mention would likely be flagged at the point of chartering. There are a lot of stopgaps already in place, but I appreciate your concern. 

Taking a look at the repo in question (I have not yet read the proposal, so I will reserve my judgement on that), I would advise that the issues being opened appear to be turning into a bit of a pile-on, which would be a CEPC concern. Critiquing proposals is entirely fine, but please refrain from spamming the repository with multiple issues on related topics, or making personal statements regarding the authors. This is not directed at you @jfinkhaeuser specifically, but if you are able to help establish a better pattern of behaviour in that group it would be appreciated.

**Comment by joepie91** [comment]
I personally find it a strange choice to prioritize tone policing a significant chunk of internet users who are rightly angry about yet another encroachment on their agency, over looking into and shooting down the proposal that prompted the response in question.

This is reminiscent of the calls for "professionalism" on the original repository - in a vacuum that might seem like a reasonable expectation, but when a well-resourced and well-spoken bad actor is trying to introduce an oppressive system into a specification, enforcing "professionalism" *really* only serves to provide cover for said oppressive system to be introduced, and I feel that that practical consequence (and the harm it does) is of rather more importance than a superficial notion of "professionalism".

Please consider carefully which outcome this approach to the issue serves.

**Comment by TzviyaSiegman** [comment]
Please comment on the proposal in https://github.com/RupertBenWiser/Web-Environment-Integrity/issues/112. This is the repo for the maintenance of the code of conduct for the W3C. We do not manage specifications or incident reporting.

**Comment by jwrosewell** [comment]
> I feel that that practical consequence (and the harm it does) is of rather more importance than a superficial notion of "professionalism".

> Please consider carefully which outcome this approach to the issue serves.

@joepie91 eloquently highlights the problem with the proposed CoC. and the existing CEPC in practice.

These documents are used in practice to provide cover for others to silence debate, as has already happened to myself, who has been banned from commenting in the TAG by @torgo despite being a paid up member of W3C and presenting views with evidence clearly and rationally and highlighting nothing of substance exists to support the TAG and W3C position.

The W3C talks about diversity and representing the interests of all stakeholders but when new stakeholders come forward does little to embrace them when their views are not aligned to the establishment.

Rather than lecturing @joepie91 and @jfinkhaeuser, inviting them into the W3C seems like the better approach. Offer free Invited Expert membership? Or is that only available to an opaque few?  Or even offering [individual membership](https://www.w3.org/Consortium/fees)?  If they join now they get to vote on the adoption of the revised CoC and suggest amendments via W3C Process 2021.

**Comment by jfinkhaeuser** [comment]
I don't feel particularly targeted, but I have to agree that tone policing in the face of injustice is itself injustice, and I will not become complicit in that.

If you don't like the tone of the comments, feel free to discuss that with the persons making them.

**Comment by roryyamm** [comment]
> Please comment on the proposal in [RupertBenWiser/Web-Environment-Integrity#112](https://github.com/RupertBenWiser/Web-Environment-Integrity/issues/112). This is the repo for the maintenance of the code of conduct for the W3C. We do not manage specifications or incident reporting.

We can't. They locked down the issues page.

**Comment by wareid** [comment]
@jwrosewell Being an invited expert to the W3C is already free, you simply need to apply for IE status to the working group you're interested in. Also, PWE is a community group, so anyone is welcome to join us any time. I know you have issues with the revised CoC, but this is not the issue for that topic.

@roryyamm I made the suggestion before that happened, I am aware now they've locked down commenting. This particular situation is challenging because this is not technically a W3C repo, it's an individual's, and while I understand they have now linked to our CEPC, the CEPC is for interpersonal issues, we don't generally provide guidance on what to do with one's issue tracker. 

@jfinkhaeuser My comments were not intended to be tone policing, and I apologize for giving that impression. I'll reiterate again at this point, I have not read the proposal so don't yet understand the issues at play. My role in this regard is to ensure that people are being respectful and non-abusive. At the end of the day, this is a technical proposal under discussion, it's not official in any sense of the word, it is hosted on a personal repo by someone seeking feedback. I understand that the community overwhelmingly does not agree with the proposal, but at this stage what seems most appropriate is to give feedback on concerns and get a diversity of feedback from the community. Personal attacks on the authors is not acceptable under our CEPC or any other code that I have looked at. I have seen people in this discussion do an excellent job of keeping their comments reasonable and focused, and I have seen people call for others to be respectful as well, I appreciate that greatly.

**Comment by mnot** [comment]
One thing to note here: that repo is _not_ in W3C space, nor does it contain work adopted by any W3C group. So its ability to claim that the CEPC applies (which implies W3C authority over it, potential consumption of W3C resources, etc.) is questionable.
