### ISSUE TITLE
3.3 Safety vs. Comfort - editorial

### ISSUE THREAD

**Issue by mnot** [w3c/PWETF#309]
The way this section is written is a bit confusing to me. Straw-man proposal (that I'm sure could be improved):

> This Code prioritizes the safety of individuals, particularly those in marginalized communities, over the comfort of others. For example, the following behaviours are presumed to be acceptable even if they make some participants uncomfortable:
>
> * Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you”
> * Communicating in a tone that is perceived by some to be uncongenial
> * Critising oppressive behaviour or assumptions, such as those that are racist, sexist, or cissexist
> 
> Note that claims of "reverse"-isms including "reverse racism," "reverse sexism," and "cisphobia" are not acceptable.

That _should_ be just an editorial change. However, it might also be good to explain the points about tone and reverse-isms a bit more.

**Comment by TzviyaSiegman** [comment]
Thanks @mnot. We will consider this. This section proved very challenging to write. I appreciate the suggestion.

**Comment by dbooth-boston** [comment]
I think this is a big improvement -- especially this part: "the following behaviours are presumed to be acceptable even if they make some participants uncomfortable".  

However, I think this bullet is still problematic:

> Note that claims of "reverse"-isms including "reverse racism," "reverse sexism," and "cisphobia" are not acceptable.

It's problematic because:

 - It's using jargon that isn't defined; and
 - It's implicitly based on, and referring to, a theory of oppression and discrimination that isn't explained.  Racism, sexism and other isms should not be acceptable regardless of whether they are "forward" or "reverse".  But if *claims* of reverse-isms are *not* acceptable, while *claims* of forward-isms *are* acceptable, the document should explain why they are treated so differently, because it is not at all obvious.

**Comment by wareid** [comment]
@dbooth-boston there's an open PR for this issue (PR #329 ), but the terms you mention do have linked definitions in the document.

**Comment by dbooth-boston** [comment]
@wareid AFAICT "reverse-ims", "reverse racism", etc. are not defined in the document.
