### ISSUE TITLE
Consider proposed revisions to CEPC

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#7]
After TPAC 2017, there were proposals for revising the CEPC. 

See email thread with attached proposals by Vlad Levantovsky beginning with:
https://lists.w3.org/Archives/Member/member-pwetf/2018JanMar/0000.html
See especially comments by @brewerj at https://lists.w3.org/Archives/Member/member-pwetf/2018JanMar/0016.html and https://lists.w3.org/Archives/Member/member-pwetf/2018JanMar/0017.html

Please read through the thread (if you have access). Vlad explained the he "tried to soften the stance and use descriptive language (instead of prescriptive) whenever possible, giving readers a reason why certain things are expected.".

**Comment by vlevantovsky** [comment]
Many folks have asked me if the new draft CEPC prepared by the Positive Work Environment Task Force back in Dec. 2017 - Jan. 2018 can be made available online for review. I think it would help our discussion if, instead of referencing an old email thread we can simply publish the draft here for this group to review. I don't have permissions to create a new file / document, but it would be an easy task for someone who has the necessary permissions to do this. The file in question (that incorporates the latest revision of that draft is attached).
[DraftCEPCforPWETF v8.pdf](https://github.com/w3c/PWETF/files/2555145/DraftCEPCforPWETF.v8.pdf)

**Comment by vlevantovsky** [comment]
As part of the PWE discussion during March 7 call, it was mentioned that evidence-based approach (where we should consider work done by other groups and what is proven to work and be acceptable policy) would be preferred. Not surprisingly, two different attempts to improve the text of CEPC - one mentioned in my previous comment [about PWETF work,](https://lists.w3.org/Archives/Member/member-pwetf/2018JanMar/0021.html) and another one prepared by @AdaRoseCannon for [Immersive Web](https://immersive-web.github.io/homepage/code-of-conduct.html) group are both based in significant parts on the work done by the TODO group (which is highly regarded in the industry) and share similar concepts and structure.

**Comment by TzviyaSiegman** [comment]
I think this can be closed per #45
