### ISSUE TITLE
review exception in "deliberate outing" section

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#83]
@jeffjaffe asked foe review of the exception clause in the following sentence from Unacceptable Behaviors section:

> Deliberate outing of any aspect of a person’s identity without their consent except as necessary to protect other community members or other vulnerable people from intentional abuse

**Comment by TzviyaSiegman** [comment]
The text is taken from [Geek Feminism anti-harassment policy](https://geekfeminism.wikia.org/wiki/Community_anti-harassment/Policy). 

We could consider changing to the type of wording included in a different CoC, such as the three bullets in [WeAllJS CoC](https://wealljs.org/code-of-conduct)

- Publishing others’ private information, such as a physical or electronic address, without explicit permission. This includes any sort of “outing” of any aspect of someone’s identity without their consent.
- Publishing screenshots or quotes, especially from identity channels, without all quoted users’ explicit consent.
- Publishing or telling others that a member belongs to a particular identity channel without asking their consent first.

I am interested in hearing feedback from @wseltzer about legal ramifications of the existing clause.

**Comment by AdaRoseCannon** [comment]
I don't want to edit the line too far from an existing code of conduct. These communities have been running under a CoC longer than we have and have experience and have evolved their code of conducts accordingly. An exception clause like this would not have been added lightly. 

The one from Geek Feminism is held in high regard and the language is used in many existing codes and I would rather keep the wording so that the source can be found via searching with search engine.

If we have to change it taking the one from the WeAllJS CoC as @TzviyaSiegman suggested would be acceptable.

**Comment by jeffjaffe** [comment]
@AdaRoseCannon here is my confusion.  The clause "except as necessary" seems to say that there are instances where "Deliberate outing of a person without their consent" is actually permissible under the proposed CEPC.

I'm having a hard time understanding when it should be ever permissible to do so.

Even if I could consider a scenario where it might be permissible to do so, I would want that scenario to be very tightly defined.  The current wording: "to protect other community members or other vulnerable people from intentional abuse" seems very subjective.  If someone outs someone else and claims that they did it to protect other community members - who decides whether it was permissible?  What are the criteria?  Without a criteria and process this becomes a path to allow outing - which I thought we wanted to forbid.

The text that Tzviya proposed does not appear to have this problem.

**Comment by AdaRoseCannon** [comment]
I've been trying to find why it was added to the original CoC without luck but from my understanding it's so that if you alert a peer that a colleague is known for sexual harassment (or worse) but doing so would out them as gay or lesbian then it is still protected.

**Comment by wareid** [comment]
I like the section as is, I think the language is pretty clear. Trying to write a CoC that factors in every possible human interaction in the history of interactions will be nearly impossible. We are working from established CoCs that have been proven to serve their communities well, I don't see why we need to change this. 

I'd add that because groups have the added protections of moderation (Chairs, Ombuds), even in a scenario where someone "outs" someone and there is a potential dispute over whether that was appropriate (like in the example Ada provides), that is where a moderator can step in to determine the intent.

**Comment by jeffjaffe** [comment]
@wareid My concern Wendy is the sequence of events could cause a problem.

Person X outs person Y (allegedly) to protect person Z.

We've created a permitted grievance.  Person Y has been outed.  They may claim that they were not a threat to person Z - so they claim that our Code has allowed them to be outed.  That seems very bad.

Your solution to solve this via Chairs and Ombuds is problematic.  First of all, they may lack the skills to determine whether person Y was really a threat to person Z.  Or the facts of the situation might make it unclear.  But the damage has been done.

Or they may conclude that person Y should not have been outed.  But the damage has been done.  And if Person X has a reasonable explanation of why they did the outing, they would not be penalized either.

Additionally, we don't generally assign the task to Chairs and Ombuds to be after the fact judges of whether an action was OK.  Rather, we ask them to facilitate a community that works well together.

**Comment by wareid** [comment]
I think you might be overthinking this scenario a little, but there's an element to your example that I think many of us with experience being involved with a situation like this will do that might mitigate this scenario. 

If Person X is concerned that Person Y has the potential to harm Person Z in some way, the first person X is going to go to is not the group or the chair or the ombudsperson, it's person Z. This is the whisper network phenomenon that many minoritised groups use to ensure safety. Person X is most definitely going to give private information to Person Z about Person Y if a threat is known. We cannot (nor do I believe we should) police a whisper network unless it causes harm. I'm not suggesting chairs are responsible for this, or should judge, what I mean is that should this scenario appear in a group, they are in place to moderate handling it. Obviously if Person Y intends to harm Person Z in a way that contravenes the CEPC, we will have policy for that. If it affects working environments, Chairs will have training to handle it. No language is going to make this disappear.

We can come up with examples for this for every single line in any CoC, it's part of the reason they're such a challenge to write, but I don't think we should be spending this much time picking apart a well-used practice. If scenarios like this were common, I would expect criteria like this would not be used, or would be amended, and we can be mindful of that.

**Comment by jeffjaffe** [comment]
@wareid I agree with you that we cannot police a whisper network.  I was not trying to say that we should police whisper networks.  I was merely saying that language which provides explicit language that permits outing could be misused.

**Comment by brewerj** [comment]
Commenting on multiple aspects of this thread: 

I do not think that we should take up language from other Codes of Conduct as is, without a clear understanding of its purpose, and awareness of potential examples for why and how the language is relevant and needed. As is, it appears that both the meaning and purpose of the exception language in the no-outing provision in our current draft may be unclear. If that's the case, then the CoC may not serve the community well enough, so it's probably useful to get it clearer and/or amend it.

Based on our discussion so far, our current language may be introducing confusion by conflating identity and behavior, and stretching the typical usage of the phrase "to out someone." In my experience, the concept of "outing" typically refers to public disclosure of an identity characteristic associated with some kind of social stigma; for instance certain types of disabilities that may not be obvious to others, but are stigmatizing in many societies; or similarly someone's LGBTQI status. My impression is that the term "outing" is not typically used to refer to behaviors that may put other potentially vulnerable people at risk, such as trolling, or sexual harassment. 

The challenging aspect may be where an individual who has a confidential identity status may also have, or be perceived as having, a repeated pattern of behavior that may put others at risk, and whether there needs to be an explicitly stated exception to the outing ban for the purpose of protecting some ability to warn people. The proposed exception to an outing ban seems to open a barn door of exceptions, and, as others have noted, opens troublesome questions of who gets to judge what kind of identity characteristics, and/or behaviors, may be a risk to others in the community.

I question whether there is a fair and appropriate way to word this type of exception to an outing ban, or to any similar provisions. The alternative language from the WeAllJS CoC seems better in that it does not include an exception, however their language also seems very specific and thereby overly narrow. I'm therefore leaning towards keeping the first half of our current text, e.g., [unacceptable behaviors] "Deliberate outing of any aspect of a person’s identity without their consent" 
[but without our current exceptions]. 

However, I proposed that we take this issue  up again when discussing procedures. For instance, if an Ombuds becomes aware of behaviors that puts others at risk, perhaps there could be an expectation that they would share that information with other Ombuds, so that there is the possibility of taking measures to ensure a safer community. It seems that that would be important to sort out, but perhaps the procedures discussion would be a better place to sort that out. 

Thanks, 
- Judy

**Comment by TzviyaSiegman** [comment]
resolved on 2020-01-09 call: change the language to "Deliberate outing of any aspect of a person’s identity without their consent."
and create new issue for ombuds and training
